; ==========================================================================
; PDDL Plan — Insertion Task
; Generated by pddl_generator.py
;   N beads  = 3
;   T sticks = 3
;   Robot    = gofa_robot
;
; Action cycle per bead:
;   1. pick_bead      — grasp bead from table
;   2. move_to_stick  — carry bead above target stick
;   3. insert_bead    — insert bead onto stick (contact-force step)
;   4. move_to_table  — return gripper to table for next bead
;
; Total actions: 12
; ==========================================================================
; --- Cycle 1: bead1 → stick1 ----------------------------------------
(pick_bead      gofa_robot bead1 table_loc)
(move_to_stick  gofa_robot bead1 table_loc abacus_loc stick1)
(insert_bead    gofa_robot bead1 stick1 abacus_loc)
(move_to_table  gofa_robot abacus_loc table_loc)

; --- Cycle 2: bead2 → stick2 ----------------------------------------
(pick_bead      gofa_robot bead2 table_loc)
(move_to_stick  gofa_robot bead2 table_loc abacus_loc stick2)
(insert_bead    gofa_robot bead2 stick2 abacus_loc)
(move_to_table  gofa_robot abacus_loc table_loc)

; --- Cycle 3: bead3 → stick3 ----------------------------------------
(pick_bead      gofa_robot bead3 table_loc)
(move_to_stick  gofa_robot bead3 table_loc abacus_loc stick3)
(insert_bead    gofa_robot bead3 stick3 abacus_loc)
(move_to_table  gofa_robot abacus_loc table_loc)

; ==========================================================================
; End of plan.
; Goal is satisfied after the last insert_bead action (step 11).
; The final move_to_table returns the robot to its home position.
; ==========================================================================
